### ISSUE TITLE
can you add a demo link ?

### ISSUE THREAD

**Issue by ghost** [mrstevedev/bbpmusiclibrary#1]
can you add a demo link ?

**Comment by mrstevedev** [comment]
Using LocalTunnel
https://shaggy-sloth-61.loca.lt/

It will be live in a month or two. It's almost done. In the meantime using local tunnel can proxy my dev server.  It will be slow because its the Next.js dev server not the build.

**Comment by wvfrm** [comment]
okay , anyways what service are you using post payment for the content(the sample pack?) delivery , is it a simple email with a download link or a protected route leading to the download page ?

**Comment by mrstevedev** [comment]
I have nodemailer as a dependency.  That was going to be my approach. I havn't implemented it yet but that is what I was going to do. Just send an email with a download link.
